<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var $viewModel \Adyen\ExpressCheckout\ViewModel\CheckoutConfig */
$viewModel = $block->getData('checkoutConfigViewModel');
$serializedCheckoutConfig = $viewModel->getSerializedCheckoutConfig();
$adyenData = $viewModel->getAdyenData();
$serializedAdyenData = json_encode($adyenData, JSON_HEX_TAG);

$script = <<<SCRIPT
    window.checkoutConfig = {$serializedCheckoutConfig};
    window.customerData = window.checkoutConfig.customerData;
    window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
    window.adyenData = {$serializedAdyenData};
SCRIPT;

echo $secureRenderer->renderTag('script', [], $script, false);
