version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
    target-branch: "main"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
    target-branch: "main"
