<?php
/**
 * @var \Adyen\ExpressCheckout\Block\ApplePay\Shortcut\Button $block
 * @var \Magento\Framework\Escaper $escaper
 */
try {
    $id = sprintf('%s%s', $block->getContainerId(), random_int(PHP_INT_MIN, PHP_INT_MAX));
} catch (Exception $e) {
    /**
     * Exception only thrown if an appropriate source of randomness cannot be found.
     * https://www.php.net/manual/en/function.random-int.php
     */
    $id = 0;
}

$config = [
    'Adyen_ExpressCheckout/js/applepay/button' => [
        'actionSuccess' => $block->getActionSuccess(),
        'storeCode' => $block->getStorecode(),
        'countryCode' => $block->getDefaultCountryCode(),
        'currency' => $block->getCurrency(),
        'merchantAccount' => $block->getMerchantAccount(),
        'format' => $block->getFormat(),
        'locale' => $block->getLocale(),
        'originkey' => $block->getOriginKey(),
        'checkoutenv' => $block->getCheckoutEnvironment(),
        'isProductView' => (bool) $block->getIsProductView()
    ]
];
?>
<div class="adyen-checkout__dropin apple-pay-button-card" id="<?= $id ?>"
     data-mage-init="<?= $escaper->escapeHtmlAttr(json_encode($config)) ?>">
</div>
