<?php
/**
 * @var \Adyen\ExpressCheckout\Block\Cart\OrderReview $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if($block->isVisible()): ?>
    <div class="amazonpay_order_review">
        <strong>Ship To</strong>
        <div class="amazonpay_order_review_details">
            <p id="amazonpay_shopper_details_values"></p>
        </div>
        <strong>Payment Method</strong>
        <div class="amazonpay_order_review_details">
            <p id="amazonpay_payment_descriptor"></p>
        </div>
    </div>
<?php endif ?>
