<?php
/**
 * @var \Adyen\ExpressCheckout\Block\Cart\OrderReview $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if($block->isVisible()): ?>
    <div class="amazonpay_order_review">
        <h3>Order Review</h3>
        <div class="amazonpay_order_review_details">
            <p id="amazonpay_shopper_details_keys"></p>
            <p id="amazonpay_shopper_details_values"></p>
        </div>
    </div>
<?php endif ?>
